# don't build tags, it's redundant
if: tag IS blank

sudo: false
language: node_js
os: linux

notifications:
  email: false

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

stages:
  - name: test
  - name: deploy

test: &test
  addons:
    chrome: stable
  script:
    - npm run e2e

jobs:
  include:
    - <<: *test
      stage: test
      node_js: 10
      name: 'Test (Linux Node v10)'
    - <<: *test
      stage: test
      node_js: 12
      name: 'Test (Linux Node v12)'
    - stage: release
      node_js: lts/*
      script:
        - npm run build
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release
