# don't build tags, it's redundant
if: tag IS blank

sudo: false
language: node_js
cache:
    directories:
        - ~/.npm
notifications:
    email: false
node_js:
    - '10'
    - '12'
script:
    - npm run build
    - npm run e2e
branches:
    except:
        - /^v\d+\.\d+\.\d+$/
addons:
    chrome: stable
